import { PublicArchitectureScenarioSchema, type PublicArchitectureScenario } from "@redline/shared";

export const blackFridayCheckoutScenario: PublicArchitectureScenario = PublicArchitectureScenarioSchema.parse({
  id: "black-friday-checkout",
  slug: "black-friday-checkout",
  title: "Black Friday Checkout Redesign",
  reviewCode: "AR-204",
  description:
    "The commerce team is preparing a redesigned checkout system for Black Friday traffic. The proposed architecture has passed an initial design meeting and now requires architecture approval before implementation. The reviewer is responsible for determining whether the design is ready to proceed.",
  difficulty: "senior",
  focusAreas: ["reliability", "scalability", "data-integrity"],
  status: "Review Requested",
  architect: { name: "Alex Chen", role: "Senior Software Engineer" },

  reviewerRole:
    "You are the senior engineer responsible for deciding whether this architecture is ready to proceed to implementation.",
  learningObjective:
    "Review a high-traffic checkout architecture and identify production risks related to reliability, scalability, and data integrity while evaluating whether the design satisfies its stated requirements.",
  instructions: [
    "Review the requirements and constraints.",
    "Inspect each important architecture component.",
    "Inspect critical data flows and dependencies.",
    "Add redlines where the proposed architecture creates production risk.",
    "Classify and explain each finding.",
    "Record notes about unresolved questions or tradeoffs.",
    "Prepare an architecture approval recommendation.",
  ],
  expectedDeliverables: [
    "Architecture redlines",
    "Risk classification",
    "Severity",
    "Supporting reasoning",
    "Reviewer notes",
    "Final approval recommendation (a later phase)",
  ],

  requirements: [
    { id: "req-create-checkout", area: "functional", summary: "Create a checkout session for the items in a customer's cart." },
    { id: "req-reserve-inventory", area: "functional", summary: "Reserve inventory for the items in the order before payment is captured." },
    { id: "req-process-payment", area: "functional", summary: "Authorize and capture payment through the existing payment provider." },
    { id: "req-create-order", area: "functional", summary: "Create a durable order record once payment succeeds." },
    { id: "req-send-confirmation", area: "functional", summary: "Send the customer an order confirmation." },
    {
      id: "req-throughput",
      area: "throughput",
      summary: "Support peak Black Friday checkout traffic.",
      target: "15,000 requests/minute",
    },
    {
      id: "req-availability",
      area: "availability",
      summary: "Checkout must remain available through the Black Friday peak window.",
      target: "99.95%",
    },
    {
      id: "req-latency",
      area: "latency",
      summary: "Checkout requests must complete quickly enough to avoid abandoned carts.",
      target: "p95 < 800 ms",
    },
    {
      id: "req-rpo",
      area: "durability",
      summary: "Order data loss must be minimal in a failure.",
      target: "RPO < 1 minute",
    },
    {
      id: "req-rto",
      area: "recovery",
      summary: "Checkout must recover quickly from a failure.",
      target: "RTO < 5 minutes",
    },
  ],

  constraints: [
    { id: "con-deadline", summary: "The redesign must launch before the Black Friday traffic window; the ship date is fixed." },
    {
      id: "con-pci",
      summary:
        "Payment processing must stay within existing PCI compliance scope; card data should not be handled directly by Redline's own services.",
    },
    {
      id: "con-postgres-expertise",
      summary: "The team has deep operational expertise in PostgreSQL and limited experience operating alternative datastores at this scale.",
    },
    { id: "con-headcount", summary: "Engineering headcount for this project is limited during the review window." },
    {
      id: "con-payment-integration",
      summary: "The design must integrate with the existing external payment provider without renegotiating the contract or switching providers.",
    },
  ],

  evidence: [
    { id: "ev-traffic-normal", category: "Traffic", label: "Normal", value: "800 checkout requests/min" },
    { id: "ev-traffic-peak", category: "Traffic", label: "Peak", value: "15,000 requests/min" },
    { id: "ev-traffic-flash", category: "Traffic", label: "Flash sale projection", value: "32,000 requests/min" },
    { id: "ev-db-primary", category: "Database", label: "Primary database", value: "PostgreSQL" },
    { id: "ev-db-connections", category: "Database", label: "Max connections", value: "500" },
    { id: "ev-db-deployment", category: "Database", label: "Deployment", value: "Single primary region" },
    { id: "ev-payment-latency", category: "Payment provider", label: "Typical latency", value: "220 ms" },
    { id: "ev-payment-p99", category: "Payment provider", label: "p99 latency", value: "1.8 s" },
  ],

  nodes: [
    { id: "web-client", category: "client", label: "Web Client", position: { x: 0, y: 260 }, summary: "Browser-based checkout UI." },
    { id: "api-gateway", category: "gateway", label: "API Gateway", position: { x: 260, y: 260 }, summary: "Entry point for all checkout requests." },
    { id: "checkout-service", category: "service", label: "Checkout Service", position: { x: 540, y: 260 }, summary: "Orchestrates the checkout flow." },
    { id: "inventory-service", category: "service", label: "Inventory Service", position: { x: 840, y: 80 }, summary: "Reserves and tracks inventory." },
    { id: "payment-provider", category: "external", label: "Payment Provider", position: { x: 840, y: 260 }, summary: "External payment authorization API." },
    { id: "postgres", category: "database", label: "Orders DB", position: { x: 840, y: 440 }, summary: "System of record for orders and inventory." },
    { id: "redis", category: "cache", label: "Redis", position: { x: 1140, y: 80 }, summary: "Inventory count cache." },
    { id: "message-queue", category: "queue", label: "Message Queue", position: { x: 1140, y: 260 }, summary: "Buffers order-created events." },
    { id: "order-worker", category: "worker", label: "Order Worker", position: { x: 1420, y: 260 }, summary: "Consumes order events for fulfillment handoff." },
    { id: "notification-service", category: "service", label: "Notification Service", position: { x: 1700, y: 260 }, summary: "Sends order confirmations." },
  ],

  edges: [
    { id: "web-client-api-gateway", source: "web-client", target: "api-gateway", label: "HTTPS", protocol: "HTTPS", mode: "synchronous" },
    { id: "api-gateway-checkout-service", source: "api-gateway", target: "checkout-service", label: "HTTPS", protocol: "HTTPS", mode: "synchronous" },
    { id: "checkout-service-inventory-service", source: "checkout-service", target: "inventory-service", label: "reserve", protocol: "HTTPS", mode: "synchronous" },
    { id: "checkout-service-payment-provider", source: "checkout-service", target: "payment-provider", label: "charge", protocol: "HTTPS", mode: "synchronous" },
    { id: "checkout-service-postgres", source: "checkout-service", target: "postgres", label: "write", protocol: "SQL", mode: "write" },
    { id: "checkout-service-message-queue", source: "checkout-service", target: "message-queue", label: "publish", protocol: "AMQP", mode: "asynchronous" },
    { id: "message-queue-order-worker", source: "message-queue", target: "order-worker", label: "consume", protocol: "AMQP", mode: "asynchronous" },
    { id: "order-worker-notification-service", source: "order-worker", target: "notification-service", label: "notify", protocol: "HTTPS", mode: "asynchronous" },
    { id: "inventory-service-redis", source: "inventory-service", target: "redis", label: "read/write", protocol: "RESP", mode: "read-write" },
    { id: "inventory-service-postgres", source: "inventory-service", target: "postgres", label: "read/write", protocol: "SQL", mode: "read-write" },
  ],

  componentDetails: [
    {
      nodeId: "web-client",
      runtime: "Browser SPA",
      responsibilities: ["Render checkout UI", "Collect payment details client-side"],
      dependencies: ["API Gateway"],
      dataOwned: [],
    },
    {
      nodeId: "api-gateway",
      runtime: "Managed API gateway",
      instances: 2,
      region: "us-east",
      scalingPolicy: "Request-count target tracking",
      responsibilities: ["TLS termination", "Request routing", "Rate limiting"],
      dependencies: ["Checkout Service"],
      dataOwned: [],
    },
    {
      nodeId: "checkout-service",
      runtime: "Node.js",
      instances: 3,
      region: "us-east",
      scalingPolicy: "CPU > 70%",
      responsibilities: ["Checkout orchestration", "Payment coordination", "Order request creation"],
      dependencies: ["Inventory Service", "Payment Provider", "Orders DB", "Message Queue"],
      dataOwned: [],
    },
    {
      nodeId: "inventory-service",
      runtime: "Node.js",
      instances: 3,
      region: "us-east",
      scalingPolicy: "CPU > 70%",
      responsibilities: ["Inventory reservation", "Stock lookups"],
      dependencies: ["Redis", "Orders DB"],
      dataOwned: ["Inventory counts"],
    },
    {
      nodeId: "payment-provider",
      runtime: "External SaaS",
      responsibilities: ["Payment authorization and capture"],
      dependencies: [],
      dataOwned: ["Cardholder payment data"],
    },
    {
      nodeId: "postgres",
      runtime: "PostgreSQL 15",
      instances: 1,
      region: "us-east",
      responsibilities: ["Orders system of record", "Inventory system of record"],
      dependencies: [],
      dataOwned: ["Orders", "Inventory counts"],
    },
    {
      nodeId: "redis",
      runtime: "Redis 7",
      instances: 1,
      region: "us-east",
      responsibilities: ["Inventory count cache"],
      dependencies: [],
      dataOwned: ["Cached inventory counts"],
    },
    {
      nodeId: "message-queue",
      runtime: "Managed message queue",
      responsibilities: ["Buffers order-created events"],
      dependencies: [],
      dataOwned: [],
    },
    {
      nodeId: "order-worker",
      runtime: "Node.js",
      instances: 2,
      region: "us-east",
      scalingPolicy: "Queue depth > 500",
      responsibilities: ["Order fulfillment handoff", "Triggers confirmation notifications"],
      dependencies: ["Message Queue", "Notification Service"],
      dataOwned: [],
    },
    {
      nodeId: "notification-service",
      runtime: "Node.js",
      instances: 2,
      region: "us-east",
      responsibilities: ["Sends checkout confirmation emails/SMS"],
      dependencies: [],
      dataOwned: [],
    },
  ],

  connectionDetails: [
    { edgeId: "web-client-api-gateway", authentication: "Session cookie" },
    { edgeId: "api-gateway-checkout-service", timeout: "5 s", authentication: "Internal service token" },
    { edgeId: "checkout-service-inventory-service", timeout: "2 s", retryPolicy: "None", authentication: "Internal service token" },
    { edgeId: "checkout-service-payment-provider", timeout: "Not specified", retryPolicy: "3 retries", authentication: "API credential" },
    { edgeId: "checkout-service-postgres", consistency: "Strong (single primary)" },
    { edgeId: "checkout-service-message-queue", payload: "OrderCreated event", consistency: "At-least-once delivery" },
    { edgeId: "message-queue-order-worker", payload: "OrderCreated event", consistency: "At-least-once delivery" },
    { edgeId: "order-worker-notification-service", timeout: "Not specified", retryPolicy: "None" },
    { edgeId: "inventory-service-redis", timeout: "50 ms" },
    { edgeId: "inventory-service-postgres", consistency: "Strong (single primary)" },
  ],
});
